-- ============================================================
-- proGym — Social: friendships, groups, leaderboard
-- ============================================================

-- ──────────────────────────────────────────────────────────
-- USERNAME: add unique constraint
-- ──────────────────────────────────────────────────────────
alter table profiles
  add constraint profiles_username_unique unique (username);

-- Allow authenticated users to see other profiles
-- (needed for friend search by username and leaderboard display)
create policy "profiles_select_authenticated" on profiles
  for select using (auth.role() = 'authenticated');


-- ──────────────────────────────────────────────────────────
-- FRIENDSHIPS
-- status: 'pending' | 'accepted'
-- requester sends the request, addressee accepts it
-- ──────────────────────────────────────────────────────────
create table if not exists friendships (
  id           uuid primary key default gen_random_uuid(),
  requester_id uuid not null references profiles(id) on delete cascade,
  addressee_id uuid not null references profiles(id) on delete cascade,
  status       text not null default 'pending'
                 check (status in ('pending', 'accepted')),
  created_at   timestamptz not null default now(),
  unique (requester_id, addressee_id)
);

alter table friendships enable row level security;

-- Both parties can see the friendship row
create policy "friendships_select" on friendships
  for select using (
    auth.uid() = requester_id or auth.uid() = addressee_id
  );

-- Only the requester can create a friendship request
create policy "friendships_insert" on friendships
  for insert with check (auth.uid() = requester_id);

-- Only the addressee can accept (update status)
create policy "friendships_update" on friendships
  for update using (auth.uid() = addressee_id);

-- Either party can remove the friendship / cancel the request
create policy "friendships_delete" on friendships
  for delete using (
    auth.uid() = requester_id or auth.uid() = addressee_id
  );


-- ──────────────────────────────────────────────────────────
-- GROUPS
-- invite_code is a short unique string generated by the app
-- ──────────────────────────────────────────────────────────
create table if not exists groups (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  invite_code text not null unique,
  created_by  uuid not null references profiles(id) on delete cascade,
  created_at  timestamptz not null default now()
);

alter table groups enable row level security;

-- Any authenticated user can look up a group (needed to join via invite code)
create policy "groups_select" on groups
  for select using (auth.role() = 'authenticated');

create policy "groups_insert" on groups
  for insert with check (auth.uid() = created_by);

create policy "groups_update" on groups
  for update using (auth.uid() = created_by);

create policy "groups_delete" on groups
  for delete using (auth.uid() = created_by);


-- ──────────────────────────────────────────────────────────
-- GROUP MEMBERS
-- ──────────────────────────────────────────────────────────
create table if not exists group_members (
  group_id  uuid not null references groups(id) on delete cascade,
  user_id   uuid not null references profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

alter table group_members enable row level security;

-- You can see the member list of any group you belong to
create policy "group_members_select" on group_members
  for select using (
    exists (
      select 1 from group_members gm
      where gm.group_id = group_members.group_id
        and gm.user_id  = auth.uid()
    )
  );

-- Users join groups themselves (or the creator adds them — both covered here)
create policy "group_members_insert" on group_members
  for insert with check (auth.uid() = user_id);

-- Users can leave a group themselves; group owner can also remove members
create policy "group_members_delete" on group_members
  for delete using (
    auth.uid() = user_id
    or exists (
      select 1 from groups
      where groups.id         = group_members.group_id
        and groups.created_by = auth.uid()
    )
  );


-- ──────────────────────────────────────────────────────────
-- LEADERBOARD RPC
-- Returns session counts for the current user's social circle
-- (friends + group mates + themselves) for a given period.
-- SECURITY DEFINER so it can read workout_logs across users.
-- ──────────────────────────────────────────────────────────
create or replace function get_leaderboard(p_period text)
returns table (
  user_id  uuid,
  name     text,
  username text,
  sessions bigint
)
language sql
security definer
stable
as $$
  with period_start as (
    select case p_period
      when 'week'  then date_trunc('week',  now())
      when 'month' then date_trunc('month', now())
      when 'year'  then date_trunc('year',  now())
      else               date_trunc('week',  now())
    end as start_at
  ),
  social_ids as (
    -- direct friends (accepted both directions)
    select requester_id as uid
      from friendships
     where addressee_id = auth.uid() and status = 'accepted'
    union
    select addressee_id as uid
      from friendships
     where requester_id = auth.uid() and status = 'accepted'
    union
    -- group mates
    select gm.user_id
      from group_members gm
     where gm.group_id in (
       select group_id from group_members where user_id = auth.uid()
     )
    union
    -- the current user themselves
    select auth.uid()
  )
  select
    p.id             as user_id,
    p.name           as name,
    p.username       as username,
    count(wl.id)     as sessions
  from social_ids s
  join profiles p on p.id = s.uid
  left join workout_logs wl
    on  wl.user_id    = s.uid
    and wl.created_at >= (select start_at from period_start)
  group by p.id, p.name, p.username
  order by sessions desc;
$$;
